# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout submodules using a PAT
              run: |
                git config --file .gitmodules --get-regexp url | while read url; do
                  git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.MY_REPO_PAT }}:${{ secrets.MY_REPO_PAT }}@github.com\//")
                done
                git submodule sync
                git submodule update --init --recursive
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - name: Copy craco.config.js
              run: php -r "file_exists('craco.config.js') || copy('craco.config.example.js', 'craco.config.js');"
            - run: yarn
            - run: yarn test
